from wsgi import app

#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV