key = "Yg&tc%DEuh6%Zc^8"
iv = "6oyZDr22E3ychjM%"

#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV