from app import app

if __name__ == '__main__':
    app.run(debug=True)
    
    #THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV
#THIS CODE CREATE BY @LUANORI_DEV